package com.github.ragnard.shen.klambda.nodes.literals;

import com.github.ragnard.shen.klambda.nodes.ExpressionNode;
import com.github.ragnard.shen.klambda.runtime.Vector;
import com.oracle.truffle.api.frame.VirtualFrame;

/** A vector value embedded in KLambda generated by Shen's compiler. */
public final class VectorNode extends ExpressionNode {
    private final Vector value;

    public VectorNode(Vector value) {
        this.value = value;
    }

    @Override
    public Object executeGeneric(VirtualFrame frame) {
        return value;
    }
}
